[package]
name = "libjuju"
version = "0.1.0"
authors = ["Kenneth Koski <kennethkoski@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "1.0"
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
