name: juju-helpers
base: core18
version: '0.1.0'
summary: Juju plugins to ease a few pain points
description: |
  Allows building a bundle as necessary and then deploying it. Also
  allows removing an existing bundle without touching the other
  applications in a given model.

grade: devel
confinement: classic

apps:
  juju-bundle:
    command: juju-bundle
  juju-kubectl:
    command: juju-kubectl

parts:
  juju-helpers:
    source: .
    source-subdir: plugins
    plugin: rust
    # https://forum.snapcraft.io/t/issue-with-rebuilding-a-rust-snap/10830
    override-build: |
      [ -f "$SNAPCRAFT_PART_INSTALL/bin/juju-*" ] && rm "$SNAPCRAFT_PART_INSTALL/bin/juju-*"
      snapcraftctl build

architectures:
  - amd64
  - arm64
  - armhf
  - i386
  - ppc64el
